# Generated by Django 6.0.3 on 2026-03-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=10)),
                ('idade', models.IntegerField()),
                ('caracteristicas', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=30)),
                ('contato', models.CharField(max_length=20)),
                ('foto', models.CharField(max_length=250)),
            ],
        ),
    ]
